// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DatatonWASM.Models;
//
//    var ingresoAnual = IngresoAnual.FromJson(jsonString);

namespace DatatonWASM.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class IngresoAnual
    {
        [JsonProperty("valor")]
        public long Valor { get; set; }

        [JsonProperty("moneda")]
        public string Moneda { get; set; }
    }

    public partial class IngresoAnual
    {
        public static IngresoAnual FromJson(string json) => JsonConvert.DeserializeObject<IngresoAnual>(json, DatatonWASM.Models.Converter.Settings);
    }

    public static class SerializeI
    {
        public static string ToJson(this IngresoAnual self) => JsonConvert.SerializeObject(self, DatatonWASM.Models.Converter.Settings);
    }

    internal static class ConverterI
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
